### PR TITLE
Use Powershell to download rustup

### PR DESCRIPTION
**Pull request by johnthagen**
Merge this before #102, #103, and #105, so we can get green builds on all PRs.

This is caused by: https://github.com/appveyor/ci/issues/1426

### CODE REVIEW

**Review by mcdenhoed — APPROVED** [review]

**Comment by mcdenhoed** [comment]
@johnthagen You should force merge this.

**Comment by mcdenhoed** [comment]
Yeah, tried, and apparently the only way I can merge PRs (that I've reviewed) into master is through the automerge button, which is disabled when checks fail.

**Comment by johnthagen** [comment]
I was missing the `-Filename` option specifier. In this case, the failed run was a legitimate failure.

**Comment by mcdenhoed** [comment]
https://www.appveyor.com/docs/how-to/download-file/

Maybe we should try one of the other options

**Pull request merged**
