### PR TITLE
Decompose Game logic

### PR DESCRIPTION
**Pull request by johnthagen**

### CODE REVIEW

**Review by mcdenhoed — APPROVED** [review]
Would it make sense to have game implement drawable rather than having a draw function hanging out in the main impl?

**Comment by johnthagen** [comment]
Would absolutely agree, and I even looked at doing it, but it needs the GlypheCache because it writes text. So the signature is different.

I couldn't think of a way around it. We could require a GlypheCache be passed in to all Drawables (so you'd always have the option to draw text or a polygon).

Any ideas on how to cleanly unify this? If we could, we could use it for story.rs and settings.rs too.

**Comment by mcdenhoed** [comment]
What if we passed the glyph cache into the game constructor instead of the run method and then just stored in in self? If that works, we could do the same in story and settings too.

**Comment by mcdenhoed** [comment]
I think it would be a little clunky to have to pass it into draw.

**Comment by johnthagen** [comment]
Yep, that can work. I had some life time struggles before, but it would be a good opportunity to learn.

**Comment by johnthagen** [comment]
Yep, that can work. I had some life time struggles before, but it would be a good opportunity to learn.

**Pull request merged**
