### PR TITLE
Use curl for downloads in AppVeyor

### PR DESCRIPTION
**Pull request by johnthagen**
#110

### CODE REVIEW

**Review by mcdenhoed — COMMENTED** [review]
Looks like there's an unexpected panic when compiling music. I assume this is unrelated to curl?

**Comment by mcdenhoed** [comment]
Ah yeah, beta and nightly are broken separately.

**Comment by johnthagen** [comment]
Looks like nightly is just `rust-fmt` I'll fix that. Do you know if the beta breakage is fixed?

**Comment by johnthagen** [comment]
Beta regression has already been reported (https://github.com/rust-lang/rust/issues/41944), so we can ignore that one for now.

**Comment by johnthagen** [comment]
`rustfmt` also happens to be broken on Windows: https://github.com/rust-lang-nursery/rustfmt/issues/1525

**Comment by johnthagen** [comment]
Beta problem has been fixed and is awaiting backport: https://github.com/rust-lang/rust/issues/41604

**Comment by johnthagen** [comment]
@mcdenhoed Looks like we're good here other than the known beta regression. I'll merge once you approve changes.

**Review by mcdenhoed — APPROVED** [review]

**Pull request merged**
