### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by mcdenhoed**

### CODE REVIEW

**Review by johnthagen — CHANGES_REQUESTED** [review]
Looks like rustfmt is still failing.

Can we actually get off nightly for rustfmt? https://github.com/rust-lang-nursery/rustfmt#quick-start

I think it would make CI much nicer to not have to chase nightly for rustfmt.

**Review by johnthagen — APPROVED** [review]

**Review by johnthagen — CHANGES_REQUESTED** [review]
Do we still need the extra nightly `RUSTFMT` build? Can we remove that now?

Or, perhaps we should make another rustfmt-only stable CI build so that it's clear that if rustfmt fails, we know it was just rustfmt issues and not actual build problems.

**Comment by mcdenhoed** [comment]
Ah, that's a good point. Yeah, we should remove it. If we're blocking merges based on rustfmt, I see no reason to have a separate stable build without it.

**Comment by mcdenhoed** [comment]
Also, is there a particular reason to do a beta build? Could probably just do a single stable build with rustfmt and a single nightly with clippy.

**Comment by mcdenhoed** [comment]
Also, is there a particular reason to do a beta build? Could probably just do a single stable build with rustfmt and a single nightly with clippy.

**Comment by johnthagen** [comment]
Beta build is mostly to help the Rust community. The idea is that builds should never break from stable to beta, and if they do it is a reportable issue/bug. This has actually happened before on `rust-belt` early on. In those cases it was real problems with an upstream crate and/or the compiler. So it's fun to actually have a chance to contribute back in that way. See [this link](https://docs.travis-ci.com/user/languages/rust/#Choosing-a-Rust-version).

> The Rust team appreciates testing against the beta and nightly channels, even if you are only targeting stable

For me the ideal builds I would like to use are:

- Stable Linux
- Stable macOS
- Beta Linux
- Nightly Linux
- Stable Linux `rustfmt`
- Nightly Linux `clippy`

Justification for this configuration:
- Linux builds are "cheap" for Travis and `rust-belt` doesn't have that many builds
- Builds run (generally, other than macOS in peek load) in parallel, so more builds doesn't slow down overall time to completion
- I like separating `rustfmt` and `clippy` into their own builds because if a build fails, it's immediately obvious why it failed based on the build type. If the `rustfmt` build fails, I know I don't need to even look at the build log, I just need to run the latest `rustfmt` locally and push.

If you'd like, we can merge your PR as is (it passes `rustfmt` and bumps the dependancies), and I'll open a separate PR to reconfigure Travis.

**Review by johnthagen — APPROVED** [review]

**Pull request merged**
